### ISSUE TITLE
Remove black floating modal from site

### ISSUE THREAD

**Issue by ketanketanketan** [tytwalker/tytwalker.github.io#6]
![screenshot](http://f.cl.ly/items/2q3B2Q0u1M451l0p2209/Screen%20Shot%202015-12-03%20at%2010.48.49%20AM.png)

This modal is the culprit: https://github.com/tytwalker/tytwalker.github.io/blob/master/index.html#L58. Deleting it would fix this issue

**Comment by tytwalker** [comment]
I already deleted that. Must find out why code isn't updating.

**Comment by tytwalker** [comment]
issue fixed.

**Comment by ketanketanketan** [comment]
The bar isn't black anymore but the modal code is still there: 

![screenshot](http://f.cl.ly/items/2q3B2Q0u1M451l0p2209/Screen%20Shot%202015-12-03%20at%2010.48.49%20AM.png)

Did you want "Work in Progress" to be floating above the site like that?
