### ISSUE TITLE
Images are not resolving in production site

### ISSUE THREAD

**Issue by ketanketanketan** [tytwalker/tytwalker.github.io#7]
Images aren't showing up because the links used are local to your machine instead of relative to the website. When you run your website locally, it's all stored on your computer inside your

Instead, the URL's for those images should be relative to the directories they sit in. 

Observe [resume site](http://ty-walker.com/resume%20website/) is unable to load the image from this url: `file:///Users/tywalker/Downloads/Background-Photo-Pack/Skillcrush_Computer.jpeg`. The website is telling whatever serve those files are sitting in to look in that folder and course there is no such folder on that computer. The image you want is on the site and it's here: `http://ty-walker.com/images/Skillcrush_Computer.jpg`

In [style.css](https://github.com/tytwalker/tytwalker.github.io/blob/master/resume%20website/style.css#L53) instead of

```
html { 
  background: url('file:///Users/tywalker/Downloads/Background-Photo-Pack/Skillcrush_Computer.jpeg');
  ...
}
```

The background url should be `../images/Skillcrush_Computer.jpg`. That tells whatever computer that style.css file is living on to look for the file somewhere closeby, specifically "up one directory" by using `../` inside of images using `images/` for a file called `Skillcrush_Computer.jpg`. 

All images that work locally will not work when they are published because then they are sitting on someone else's computer, in this case Github's computers. So we need to use relative paths that work in both cases.

**Comment by tytwalker** [comment]
ok thank you. issue fixed.
